Restaurant Page project is finished
elmejdki/Restaurant-page pull request #1
Opened 2020-10-02 22:50 UTC by elmejdki

I kindly request to review my project :smiley: this is the JavaScript Restaurant page project, where have followed the next steps:
:point_down: :point_down: :point_down: :point_down:
- I have used ES6 modules,
- Set up WebPack properly,
- Developed the Four pages using vanilla JavaScript,
- And deployed to GitHub pages as suggested by the OdinProject.

2020-10-03 03:57 UTC, sumancrest0001 commented
**Status: Changes required :gear:
Hello @elmejdki,** Your file structure and code look good but I had a problem while running it. There are small changes required to get approved. Let's consider the following points.

[Required] The built js file should be main.js, not bundle.js. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/dist_requirement.png)

[Required] I got the following error while running the project. Let me know whether it is running correctly on your machine or not.
![Screenshot from 2020-10-03 09-33-04](https://user-images.githubusercontent.com/37747619/94982690-59673c00-055c-11eb-83dc-2a783f5fac76.png)

[Required] Please add installation and running steps in the readme file to run the project.

[Optional] Live link is not added correctly in the readme file. Please add if you have.

2020-10-03 03:58 UTC, sumancrest0001 requested changes
**Make the required changes and send it for another review. If you have any query feel free to message me on slack. Suman Shrestha
Happy coding !!!**

2020-10-04 18:02 UTC, elmejdki commented
## Hi, @sumancrest0001 thank you very much for your code review.

- I have changed the bundle file name to main.js

- eventually, I don't have that error at all, maybe you forgot to run npm install that's why you are getting that error.

- I have added the installation and running steps to the readme file.

- for the live link I had a typo before now it's fixed, you can check it.

### Best Regards.

2020-10-04 21:00 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @elmejdki, congratulations :100: Having fixed all the comments made by the previous TSE :+1: I HEREBY APPROVE THE PROJECT. Congratulations go ahead and merge into development :1st_place_medal: 

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-10-04 21:00 UTC, addod19 commented on README.md
> +_You may have some issues with the `image-webpack-loader`  but that depend on your operating system each operating system has his own way to solve if you goggled it just for some couple minutes I'm s
[OPTIONAL]
- I think this part of the text should rather be in the PR. Congratulations :fireworks:

2020-10-05 01:39 UTC, elmejdki commented on README.md
> +_You may have some issues with the `image-webpack-loader`  but that depend on your operating system each operating system has his own way to solve if you goggled it just for some couple minutes I'm s
_I have already thought of that but not every user of the app will look in the PR's most of the users read the readme only._

2020-10-05 01:40 UTC, merged